# -*- coding: utf-8 -*-
"""LockerCombination

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlR_3l8smkwES9aQdPZmjzmr__c0M7sM
"""

import random

def lockerCombo():
  myName = input('Your First name is: ')
  num1 = random.randint(0, 39)
  num2 = random.randint(0, 39)
  num3 = random.randint(0, 39)
  print(num1)
  print(num2)
  print(num3)
  print(myName, "'s locker combination is ", num1,"-",num2,"-",num3)
  if num1 == num2 or num2 == num3:
    print("Please try again, this is not a valid combination !!")
  else:
    print("This combination will work !!")

lockerCombo()