# -*- coding: utf-8 -*-
"""restaurant_specificationLouisKeller

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Hgyw5fMvbuuyxk_fgBVE1lMzIeIJBQ-
"""

vegetarian = False
vegan = False
gluten_free = False
Question1 = input("Is anyone in your party a vegetarian :")
if Question1 == "yes":
  vegetarian = True
Question2 = input("Is anyone in your party a vegan :")
if Question2 == "yes":
  vegan = True
Question3 = input("Is anyone in your party a Gluten Free :")
if Question3 == "yes":
  gluten_free = True
print()
print("Here are your restaurant choices:")
print()
if not vegetarian and not vegan and not gluten_free:
  print("Joe's Gourmet Butgers \nMama's Fine Italian\n Main Street Pizza \nCorner Cafe \nChef's Kitchen")
elif vegetarian and not vegan and not gluten_free:
  print("Mama's Fine Italian\n Main Street Pizza \nCorner Cafe \nChef's Kitchen")
elif not vegetarian and not vegan and gluten_free:
  print("Main Street Pizza \nCorner Cafe \nChef's Kitchen")
elif vegetarian and not vegan and gluten_free:
  print("Main Street Pizza \nCorner Cafe \nChef's Kitchen")
elif not vegetarian and vegan and not gluten_free:
  print("Corner Cafe \nChef's Kitchen")
elif not vegetarian and vegan and gluten_free:
  print("Corner Cafe \nChef's Kitchen")
elif vegetarian and vegan and not gluten_free:
  print("Corner Cafe \nChef's Kitchen")
elif vegetarian and vegan and gluten_free:
  print("Corner Cafe \nChef's Kitchen")